Repository ministryofjustice/Claim-for-Crown-Court-Defence, pull requests merged in 2018-06, with the labels that each got.

#2370 Warrant fee info in final claims
  app/assets/javascripts/modules/show-hide-content.js
  app/controllers/external_users/advocates/claims_controller.rb
  app/controllers/external_users/claims_controller.rb
  app/controllers/external_users/litigators/claims_controller.rb
  app/models/claim/advocate_claim.rb
  app/models/claim/advocate_interim_claim.rb
  app/models/claim/base_claim.rb
  app/models/claim/interim_claim.rb
  app/models/claim/litigator_claim.rb
  app/models/claim/transfer_claim.rb
  app/models/interim_claim_info.rb
  app/presenters/claim/advocate_claim_presenter.rb
  app/presenters/claim/base_claim_presenter.rb
  app/presenters/claim/litigator_claim_presenter.rb
  app/presenters/interim_claim_info_presenter.rb
  app/validators/claim/advocate_claim_sub_model_validator.rb
  app/validators/claim/litigator_claim_sub_model_validator.rb
  app/validators/interim_claim_info_validator.rb
  app/views/external_users/advocates/claims/_miscellaneous_fees_form_step.html.haml
  app/views/external_users/claims/interim_claim_info/_fields.html.haml
  app/views/external_users/claims/interim_claim_info/_summary.html.haml
  app/views/external_users/claims/misc_fees/_summary.html.haml
  app/views/external_users/litigators/claims/_miscellaneous_fees_form_step.html.haml
  app/views/shared/_summary_agfs.html.haml
  app/views/shared/_summary_lgfs.html.haml
  config/locales/en.yml
  config/locales/error_messages.en.yml
  db/migrate/20180515140528_create_interim_claim_info.rb
  db/schema.rb
  spec/api/entities/ccr/adapted_fixed_fee_spec.rb
  spec/api/v1/external_users/fee_spec.rb
  spec/factories/claim/litigator_claims.rb
  spec/factories/fees.rb
  spec/factories/interim_claim_info.rb
  spec/models/claim/advocate_claim_spec.rb
  spec/models/claim/base_claim_spec.rb
  spec/models/claims/totals_spec.rb
  spec/models/fee/base_fee_spec.rb
  spec/presenters/claim/advocate_claim_presenter_spec.rb
  spec/presenters/claim/advocate_interim_claim_presenter_spec.rb
  spec/presenters/claim/interim_claim_presenter_spec.rb
  spec/presenters/claim/litigator_claim_presenter_spec.rb
  spec/presenters/claim/transfer_claim_presenter_spec.rb
  spec/presenters/interim_claim_info_presenter_spec.rb
  spec/support/shared_examples/presenters/base_claim_shared_examples.rb
  spec/validators/claim/advocate_claim_sub_model_validator_spec.rb
  spec/validators/claim/litigator_claim_sub_model_validator_spec.rb
  spec/validators/fee/base_fee_validator_spec.rb
  spec/validators/interim_claim_info_validator_spec.rb
Labels: requires migration

#2372 CBO-130 Numbered lists plugin
  app/assets/javascripts/application.js
  app/assets/javascripts/plugins/jquery.numbered.elements.js
  app/assets/stylesheets/v1/application.css.scss
  app/assets/stylesheets/v2/_buttons.scss
  app/views/external_users/claims/expenses/_expense_fields.html.haml
  app/views/external_users/claims/expenses/_fields.html.haml
  app/views/external_users/claims/fixed_fees/_fields.html.haml
  app/views/external_users/claims/fixed_fees/_fixed_fee_fields.html.haml
  app/views/external_users/claims/misc_fees/_fields.html.haml
  app/views/external_users/claims/misc_fees/_misc_fee_fields.html.haml
  features/claims/advocate/advocate_admin_trial_claim_edit_submit.feature
  features/page_objects/sections/typed_fee_section.rb
  features/step_definitions/advocate_claim_steps.rb
  spec/javascripts/modules-sidebar_spec.js
Labels: enhancement, frontend, in progress

#2388 Add missing index for defendant_id foreign key on rep orders
  db/migrate/20180531110653_add_defendant_id_index_to_representation_orders.rb
  db/schema.rb
Labels: ready, requires migration

#2384 Zero cost redeterminations
  app/models/claims/state_machine.rb
  features/refuse_claim.feature
  features/step_definitions/authorise_claim_steps.rb
  features/step_definitions/messaging_steps.rb
  spec/models/claims/state_machine_spec.rb
Labels: in progress

#2380 Tweak error messages for net amounts
  config/locales/error_messages.en.yml
  spec/api/v1/external_users/fee_spec.rb
Labels: in progress

#2391 Amend link and copy for special prep form link
  config/locales/en.yml
Labels: in progress

#2390 Add test profiler for factory bot
  Gemfile
  Gemfile.lock
Labels: in progress

#2395 Revert "Quantity for a fee needs to be greater or equal than 1"
  app/validators/fee/base_fee_validator.rb
  app/validators/fee/basic_fee_validator.rb
  spec/support/shared_examples_for_fee_validators.rb
  spec/validators/fee/base_fee_validator_spec.rb
  spec/validators/fee/fixed_fee_validator_spec.rb
Labels: in progress

#2393 AGFS Warrants filter
  .rubocop.yml
  app/controllers/case_workers/admin/allocations_controller.rb
  app/interfaces/api/entities/search_result.rb
  app/interfaces/api/v2/query_helper.rb
  app/interfaces/api/v2/search.rb
  app/views/case_workers/admin/allocations/_case_type_filters.html.haml
  app/views/case_workers/admin/allocations/_filter_tasks.html.haml
  spec/api/entities/search_result_spec.rb
  spec/api/v2/search_spec.rb
Labels: in progress

#2392 Add validations to representation order date
  app/models/claim/base_claim.rb
  app/services/ccr/daily_attendance_adapter.rb
  app/validators/claim/base_claim_validator.rb
  app/validators/fee/base_fee_validator.rb
  app/validators/representation_order_validator.rb
  app/views/external_users/claims/case_details/_summary.html.haml
  app/views/shared/_claim.html.haml
  config/locales/error_messages.en.yml
  spec/api/entities/ccr/adapted_basic_fee_spec.rb
  spec/api/v1/external_users/fee_spec.rb
  spec/controllers/external_users/litigators/claims_controller_spec.rb
  spec/models/claim/base_claim_spec.rb
  spec/services/ccr/daily_attendance_adapter_spec.rb
  spec/validators/fee/base_fee_validator_spec.rb
  spec/validators/representation_order_date_validator_spec.rb
Labels: in progress

#2398 Amend contact email addresses for service
  app/views/pages/contact_us.html.haml
  config/settings.yml
Labels: in progress

#2400 Display only non-zero basic fees in the summary page
  app/views/external_users/claims/basic_fees/_summary.html.haml
Labels: in progress

#2389 CBO-101: LGFS Grad fees design implementation
  app/assets/stylesheets/v2/_denote.scss
  app/assets/stylesheets/v2/_forms.scss
  app/views/external_users/claims/graduated_fees/_fields.html.haml
  app/views/external_users/litigators/claims/_graduated_fees_form_step.html.haml
  config/locales/en.yml
  features/claims/litigator/litigator_trial_claim_draft_submit.feature
  features/page_objects/litigator_claim_form_page.rb
  features/step_definitions/litigator_claim_steps.rb
Labels: donotmerge, enhancement, frontend, in progress

#2403 Fix some N+1 queries in the external users claims page
  app/controllers/external_users/claims_controller.rb
Labels: in progress

#2405 Working un-archiving
  app/controllers/external_users/claims_controller.rb
  lib/previous_version_of_claim.rb
  spec/controllers/external_users/claims_controller_spec.rb
  spec/lib/previous_version_of_claim_spec.rb
Labels: in progress

#2404 Manage provider page redesign
  app/assets/javascripts/application.js
  app/assets/javascripts/modules/Modules.Providers.js
  app/assets/stylesheets/v2/_breadcrumbs.scss
  app/assets/stylesheets/v2/_links.scss
  app/assets/stylesheets/v2/_mod-provider-details.scss
  app/assets/stylesheets/v2/_panels.scss
  app/assets/stylesheets/v2/application.scss
  app/controllers/concerns/provider_admin_concern.rb
  app/controllers/external_users/admin/providers_controller.rb
  app/controllers/super_admins/providers_controller.rb
  app/models/provider.rb
  app/models/supplier_number.rb
  app/services/external_users/create_user.rb
  app/validators/supplier_number_sub_model_validator.rb
  app/views/external_users/admin/providers/edit.html.haml
  app/views/shared/_supplier_number_fields.html.haml
  app/views/shared/_supplier_numbers.html.haml
  app/views/shared/providers/_form.html.haml
  app/views/shared/providers/edit.html.haml
  app/views/shared/providers/new.html.haml
  app/views/super_admins/providers/_form.html.haml
  app/views/super_admins/providers/edit.html.haml
  app/views/super_admins/providers/new.html.haml
  config/initializers/regexps.rb
  config/locales/en.yml
  db/migrate/20180612133535_add_new_fields_to_suppliers.rb
  db/schema.rb
  spec/controllers/super_admins/providers_controller_spec.rb
  spec/factories/providers.rb
  spec/javascripts/modules-providers_spec.js
  spec/models/provider_spec.rb
  spec/models/supplier_number_spec.rb
  spec/support/roles.rb
Labels: in progress

#2397 Remove unused allocation components.
  app/controllers/case_workers/admin/allocations_controller.rb
  app/views/case_workers/admin/allocations/_case_type_filters.html.haml
  config/locales/en.yml
Labels: in progress

#2401 Validate rep order against cracked dates
  app/models/claim/advocate_claim.rb
  app/validators/representation_order_validator.rb
  config/locales/error_messages.en.yml
  spec/factories/case_types.rb
  spec/validators/representation_order_date_validator_spec.rb
Labels: in progress
