Repository ministryofjustice/Claim-for-Crown-Court-Defence, pull requests merged in 2018-03, with the labels that each got.

#2255 Expose transfer claims on CCLF JSON API
  Gemfile
  Gemfile.lock
  app/interfaces/api/entities/cclf/adapted_expense.rb
  app/interfaces/api/entities/cclf/adapted_transfer_fee.rb
  app/interfaces/api/entities/cclf/transfer_claim.rb
  app/models/claim/transfer_brain.rb
  app/models/claim/transfer_brain_data_item.rb
  app/models/claim/transfer_brain_data_item_collection.rb
  app/models/claim/transfer_detail.rb
  app/services/cclf/case_type_adapter.rb
  app/services/cclf/fee/transfer_fee_adapter.rb
  config/transfer_brain_data_items.csv
  lib/extensions/hash_extension.rb
  spec/api/entities/cclf/adapted_disbursement_spec.rb
  spec/api/entities/cclf/adapted_expense_spec.rb
  spec/api/entities/cclf/adapted_fixed_fee_spec.rb
  spec/api/entities/cclf/adapted_graduated_fee_spec.rb
  spec/api/entities/cclf/adapted_misc_fee_spec.rb
  spec/api/entities/cclf/adapted_transfer_fee_spec.rb
  spec/api/entities/cclf/adapted_warrant_fee_spec.rb
  spec/api/entities/cclf/case_type_spec.rb
  spec/api/v2/cclf_claim_spec.rb
  spec/data/transfer_brain_data_attributes.json
  spec/factories/claim/transfer_claims.rb
  spec/factories/claim/transfer_details.rb
  spec/factories/fee_types.rb
  spec/lib/extensions/hash_extension_spec.rb
  spec/models/claim/transfer_brain_data_item_collection_spec.rb
  spec/models/claim/transfer_brain_data_item_spec.rb
  spec/models/claim/transfer_brain_spec.rb
  spec/services/cclf/case_type_adapter_spec.rb
  spec/services/cclf/fee/transfer_fee_adapter_spec.rb
  spec/support/concerns/cclf/bill_scenario_helpers.rb
  spec/support/matchers/custom_matchers.rb
  spec/support/matchers/general_matchers.rb
  spec/support/matchers/hash_matchers.rb
  spec/support/transfer_brain_helpers.rb
  spec/validators/claim/transfer_claim_validator_spec.rb
Labels: donotmerge

#2282 Sidebar: Show / Hide on pages as required
  app/presenters/claim/base_claim_presenter.rb
  app/views/external_users/advocates/claims/edit.html.haml
  app/views/external_users/advocates/claims/new.html.haml
  app/views/external_users/advocates/interim_claims/edit.html.haml
  app/views/external_users/advocates/interim_claims/new.html.haml
  app/views/external_users/claims/_form_layout_wrapper.haml
  app/views/external_users/litigators/claims/edit.html.haml
  app/views/external_users/litigators/claims/new.html.haml
  app/views/external_users/litigators/interim_claims/edit.html.haml
  app/views/external_users/litigators/interim_claims/new.html.haml
  app/views/external_users/litigators/transfer_claims/edit.html.haml
  app/views/external_users/litigators/transfer_claims/new.html.haml
  app/views/external_users/litigators/transfer_claims/original_transfer_claim_new.html.haml
  spec/presenters/base_claim_presenter_spec.rb
Labels: enhancement, frontend

#2284 Sidebar: Show / Hide on pages as required
  app/views/external_users/claims/interim_fee/_fields.html.haml
  app/views/external_users/litigators/interim_claims/_additional_information_form_step.html.haml
  app/views/external_users/litigators/interim_claims/_interim_fees_form_step.html.haml
  app/views/external_users/litigators/interim_claims/_supporting_evidence_form_step.html.haml
  config/locales/en.yml
Labels: enhancement, frontend, ready
