Repository ministryofjustice/Claim-for-Crown-Court-Defence, pull requests merged in 2018-11, with the labels that each got.

#2527 CBO-308 Missing basic fee dates on AGFS graduated fees page + dynamic date labels
  app/assets/javascripts/modules/external_users/claims/BasicFeeDateCtrl.js
  app/assets/javascripts/modules/external_users/claims/BlockHelpers.js
  app/assets/javascripts/modules/external_users/claims/CocoonHelper.js
  app/assets/stylesheets/v1/moj/_tables.scss
  app/helpers/external_users/claims_helper.rb
  app/presenters/fee/base_fee_presenter.rb
  app/presenters/fee/interim_fee_presenter.rb
  app/views/external_users/claims/_date_attended_fields.html.haml
  app/views/external_users/claims/_summary_fee.html.haml
  app/views/external_users/claims/_summary_fees.html.haml
  app/views/external_users/claims/basic_fees/_basic_fee_fields.html.haml
  app/views/external_users/claims/basic_fees/_basic_fee_fields_primary.html.haml
  app/views/external_users/claims/basic_fees/_dates_attended.html.haml
  app/views/external_users/claims/basic_fees/_fields.html.haml
  app/views/external_users/claims/basic_fees/_first_date_display.html.haml
  app/views/shared/_summary_agfs.html.haml
  config/locales/en.yml
  features/claims/advocate/scheme_nine/advocate_claim_draft_edit_submit.feature
  features/step_definitions/common_steps.rb
  spec/helpers/external_users/claims_helper_spec.rb
  spec/javascripts/BasicFeeDateCtrl_spec.js
  spec/javascripts/helpers-sidebar_spec.js
Labels: enhancement, frontend

#2557 CBO-349 View refactor for new design
  app/assets/javascripts/modules/case_worker/admin/Modules.ManagementInformation.js
  app/assets/javascripts/modules/case_worker/admin/management_information.js
  app/views/case_workers/admin/management_information/index.html.haml
  config/locales/en.yml
  spec/javascripts/Modules.MangementInformation_spec.js
Labels: donotmerge, enhancement, frontend, in progress

#2561 CBO-425: Update total for key up event
  app/assets/javascripts/modules/external_users/claims/BlockHelpers.js
  app/views/external_users/claims/fixed_fees/_fixed_fee_fields.html.haml
  app/views/external_users/claims/misc_fees/_misc_fee_fields.html.haml
  spec/javascripts/helpers-sidebar_spec.js
Labels: enhancement, frontend, ready

#2558 CBO-458 : MAAT number validation
  app/validators/representation_order_validator.rb
  config/locales/en.yml
  config/settings.yml
  features/step_definitions/common_claim_steps.rb
  spec/api/entities/ccr/defendant_spec.rb
  spec/api/entities/ccr/representation_order_spec.rb
  spec/api/entities/defendant_spec.rb
  spec/api/v1/external_users/representation_order_spec.rb
  spec/controllers/external_users/advocates/claims_controller_spec.rb
  spec/controllers/external_users/litigators/claims_controller_spec.rb
  spec/controllers/external_users/litigators/interim_claims_controller_spec.rb
  spec/controllers/external_users/litigators/transfer_claims_controller_spec.rb
  spec/examples/exported_claim.json
  spec/examples/exported_claim_with_basic_error.json
  spec/examples/exported_claim_with_errors.json
  spec/examples/exported_claim_with_nulls.json
  spec/examples/exported_claim_with_schema_error.json
  spec/examples/exported_claims.json
  spec/examples/exported_claims_with_errors.json
  spec/examples/exported_claims_with_errors_2.json
  spec/examples/invalid_fee_type_id.json
  spec/examples/invalid_utf8.json
  spec/factories/claim/deterministic_claim.rb
  spec/factories/representation_orders.rb
  spec/models/json_document_importer_spec.rb
  spec/models/representation_order_spec.rb
  spec/support/api/claims/base_claim_test.rb
Labels: donotmerge, ready

#2568 Add missing LGFS API integration tests
  spec/api/v1/external_users/claims/integration/litigator_claim_creation.rb
  spec/factories/offences.rb
Labels: ready

#2572 Use unpresented fee rate for LGFS fixed fee rate
  app/views/external_users/claims/fixed_fees/litigators/_fields.html.haml
Labels: bug

#2577 CBO-459: Fixing a colour leaking out to body copy
  app/assets/javascripts/modules/Modules.AllocationDataTable.js
  app/assets/stylesheets/v1/moj/_tables.scss
  app/views/case_workers/admin/allocations/_re_allocation.html.haml
  app/views/case_workers/claims/_claims_list.html.haml
  spec/javascripts/Modules.AllocationDataTable_spec.js
Labels: bug, frontend, ready

#2578 Improve indexes
  db/migrate/20181123101017_add_index_to_claims_on_uuid.rb
  db/migrate/20181123101919_add_deleted_at_index_to_claims.rb
  db/migrate/20181123102020_add_claim_id_index_to_determinations.rb
  db/schema.rb
Labels: requires migration

#2579 CBO-476 Seed the AJAX request with the current selected value
  app/assets/javascripts/modules/Modules.AllocationDataTable.js
  app/assets/javascripts/modules/Modules.AllocationScheme.js
  app/assets/javascripts/modules/Modules.DataTables.js
  spec/javascripts/Modules.AllocationDataTable_spec.js
Labels: bug, frontend, ready
