Repository ministryofjustice/Claim-for-Crown-Court-Defence, pull requests merged in 2018-09, with the labels that each got.

#2463 CBO-280: Expenses additional information
  app/assets/stylesheets/v1/application.css.scss
  app/assets/stylesheets/v1/moj/_accordion.scss
  app/assets/stylesheets/v1/moj/_panels.scss
  app/controllers/external_users/claims_controller.rb
  app/views/external_users/claims/expenses/_fields.html.haml
  app/views/external_users/claims/expenses/_summary.html.haml
  app/views/external_users/claims/expenses/_textarea_additional_info.html.haml
  app/views/shared/_claim_accordion.html.haml
  app/views/shared/_summary_agfs.html.haml
  app/views/shared/_summary_lgfs.html.haml
  app/views/shared/summary/_expenses.html.haml
  app/views/shared/summary/expenses/index.html.haml
  config/locales/en.yml
  db/migrate/20180823134645_add_travel_expense_additional_info_to_claim.rb
  db/schema.rb
  features/claims/advocate/scheme_ten/advocate_fixed_fee_claim_submit.feature
  features/page_objects/claim_form_page.rb
  features/step_definitions/litigator_claim_steps.rb
Labels: data migration, enhancement

#2468 CBO-335 Changes to validation for travel expenses
  app/validators/expense_v2_validator.rb
  config/locales/error_messages.en.yml
  features/step_definitions/litigator_claim_steps.rb
  spec/api/v1/external_users/expense_spec.rb
  spec/support/validation_helpers.rb
  spec/validators/claim/advocate_interim_claim_web_validations_spec.rb
  spec/validators/expense_validator_spec.rb
Labels: WIP, bug, donotmerge

#2495 CBO-356: Fix basic fee JS calculation
  app/assets/javascripts/application.js
  app/views/external_users/claims/basic_fees/_basic_fee_fields.html.haml
Labels: bug
