Repository ministryofjustice/Claim-for-Crown-Court-Defence, pull requests merged in 2018-04, with the labels that each got.

#2301 [AGFS fee reform] Extra changes
  app/assets/javascripts/application.js
  app/assets/javascripts/modules/Modules.Autocomplete.js
  app/models/claim/advocate_claim.rb
  app/models/offence.rb
  app/presenters/fee/basic_fee_presenter.rb
  app/services/fee_reform/search_offences.rb
  app/views/external_users/certifications/new.html.haml
  app/views/external_users/claims/basic_fees/_basic_fee_calculated_fields.html.haml
  app/views/external_users/claims/basic_fees/_basic_fee_uncalculated_fields.html.haml
  app/views/external_users/claims/basic_fees/_fields.html.haml
  app/views/external_users/claims/defendants/_defendant_fields.html.haml
  app/views/external_users/claims/defendants/_fields.html.haml
  app/views/external_users/claims/offence_details/_fee_reform_fields.html.haml
  app/views/external_users/claims/offence_details/_fee_reform_summary.html.haml
  app/views/external_users/claims/supporting_documents/_new.html.haml
  config/locales/en.yml
  db/migrate/20180329145753_add_priority_to_fee_types.rb
  db/schema.rb
  db/seeds/fee_types/csv_row_mapper.rb
  db/seeds/fee_types/csv_seeder.rb
  lib/assets/data/fee_types.csv
  spec/factories/fee_types.rb
  spec/factories/fees.rb
  spec/models/claim/advocate_claim_spec.rb
  spec/presenters/fee/basic_fee_presenter_spec.rb
  spec/services/fee_reform/search_offences_spec.rb
Labels: requires migration

#2325 Handle deprecation warning on old migrations adding timestamps
  db/migrate/20150325120724_create_chambers.rb
  db/migrate/20150325142122_create_claims.rb
  db/migrate/20150325144103_create_case_worker_claims.rb
  db/migrate/20150326114342_create_fee_types.rb
  db/migrate/20150326115934_create_fees.rb
  db/migrate/20150326140238_create_expense_types.rb
  db/migrate/20150326140817_create_expenses.rb
  db/migrate/20150326145555_create_defendants.rb
  db/migrate/20150327103635_devise_create_users.rb
  db/migrate/20150330084305_create_courts.rb
  db/migrate/20150331133748_create_documents.rb
  db/migrate/20150423082903_create_document_types.rb
  db/migrate/20150423142919_create_offences.rb
  db/migrate/20150424132253_create_advocates.rb
  db/migrate/20150424140231_create_case_workers.rb
  db/migrate/20150428123404_create_offence_classes.rb
  db/migrate/20150430115328_create_schemes.rb
  db/migrate/20150527102833_create_messages.rb
  db/migrate/20150602131128_create_dates_attended.rb
  db/migrate/20150604143054_create_user_message_statuses.rb
  db/migrate/20150608154716_create_representation_orders.rb
  db/migrate/20150610154552_create_evidence_list_item_claims.rb
  db/migrate/20150616093010_drop_evidence_list_item_claims_table.rb
  db/migrate/20150616094245_create_document_type_claims_table.rb
  db/migrate/20150625122755_drop_document_types.rb
  db/migrate/20150702131509_create_locations.rb
  db/migrate/20150728093252_add_vat_rates_table.rb
  db/migrate/20150806090257_create_determinations.rb
  db/migrate/20150813142826_create_case_types_table.rb
  db/migrate/20150819095328_create_certifications.rb
  db/migrate/20151115214327_create_super_admins.rb
  db/migrate/20160119133632_create_certification_types.rb
  db/migrate/20160309115141_create_disbursement_types.rb
  db/migrate/20160309135448_create_disbursements.rb
  db/migrate/20171111113526_create_injection_attempts.rb
Labels: ready

#2328 Add spec for scheme 10 fee api submission
  app/models/claim/advocate_claim.rb
  config/settings.yml
  spec/api/v1/external_users/fee_spec.rb
  spec/factories/claim/advocate_claims.rb
  spec/factories/claim/claim_factory_helpers.rb
  spec/factories/fee_types.rb
  spec/models/json_document_importer_spec.rb
Labels: bug, ready

#2332 Split Ground Hearing fee into whole and half day
  lib/assets/data/fee_types.csv
Labels: data migration

#2335 Sidebar calculations: VAT vs No VAT
  app/views/external_users/claims/_lgfs_final_claim_sidebar.html.haml
  app/views/external_users/claims/_lgfs_interim_claim_sidebar.html.haml
  app/views/external_users/claims/_lgfs_transfer_claim_sidebar.html.haml
Labels: bug, frontend, ready

#2333 Offences scheme 10 - design changes
  app/assets/javascripts/modules/Modules.Autocomplete.js
  app/assets/stylesheets/application.css.scss
  app/assets/stylesheets/moj/_autocomplete.scss
  app/views/external_users/claims/_form_layout_wrapper.haml
  app/views/external_users/claims/offence_details/_fee_reform_fields.html.haml
  config/locales/en.yml
Labels: frontend, ready

#2336 Merge supporting evidence and additional information pages
  app/models/claim/advocate_claim.rb
  app/models/claim/advocate_interim_claim.rb
  app/models/claim/interim_claim.rb
  app/models/claim/litigator_claim.rb
  app/models/claim/transfer_claim.rb
  app/validators/claim/advocate_claim_sub_model_validator.rb
  app/validators/claim/advocate_claim_validator.rb
  app/validators/claim/interim_claim_validator.rb
  app/validators/claim/litigator_claim_validator.rb
  app/validators/claim/transfer_claim_validator.rb
  app/views/external_users/advocates/claims/_additional_information_form_step.html.haml
  app/views/external_users/advocates/claims/_supporting_evidence_form_step.html.haml
  app/views/external_users/advocates/interim_claims/_additional_information_form_step.html.haml
  app/views/external_users/advocates/interim_claims/_supporting_evidence_form_step.html.haml
  app/views/external_users/litigators/claims/_additional_information_form_step.html.haml
  app/views/external_users/litigators/claims/_supporting_evidence_form_step.html.haml
  app/views/external_users/litigators/interim_claims/_additional_information_form_step.html.haml
  app/views/external_users/litigators/interim_claims/_supporting_evidence_form_step.html.haml
  app/views/external_users/litigators/transfer_claims/_additional_information_form_step.html.haml
  app/views/external_users/litigators/transfer_claims/_supporting_evidence_form_step.html.haml
  features/claims/advocate/advocate_admin_trial_claim_edit_submit.feature
  features/claims/advocate/advocate_claim_draft_edit_submit.feature
  features/claims/advocate/advocate_contempt_claim_edit_submit.feature
  features/claims/litigator/interim_trial_claim_draft_submit.feature
  features/claims/litigator/interim_trial_warrant_claim_draft_submit.feature
  features/claims/litigator/litigator_contempt_claim_draft_submit.feature
  features/claims/litigator/litigator_contempt_claim_with_errors_submit.feature
  features/claims/litigator/litigator_trial_claim_draft_submit.feature
  features/claims/litigator/transfer_claim_draft_submit.feature
  features/step_definitions/common_steps.rb
Labels: ready

#2334 Api scheme ten endpoint updates
  app/interfaces/api/v1/dropdown_data.rb
  app/views/pages/api_release_notes.html.haml
  spec/api/v1/dropdown_data_spec.rb
Labels: api

#2338 Fix flakey test related with non unique location generation
  spec/factories/locations.rb
Labels: ready

#2345 Advocate category validation Scheme 10
  app/interfaces/api/v1/external_users/claims/advocate_claim.rb
  app/services/claims/fetch_eligible_advocate_categories.rb
  spec/factories/claim/api_claims.rb
  spec/services/claims/fetch_eligible_advocate_categories_spec.rb
Labels: api, ready

#2337 Offence Search feature
  app/assets/javascripts/application.js
  app/assets/javascripts/modules/Modules.OffenceSearchInput.js
  app/assets/javascripts/modules/Modules.OffenceSearchView.js
  app/assets/javascripts/modules/Modules.OffenceSelectedView.js
  app/assets/javascripts/modules/external_users/claims/NewClaim.js
  app/assets/stylesheets/application.css.scss
  app/assets/stylesheets/moj/_autocomplete.scss
  app/services/fee_reform/search_offences.rb
  app/views/external_users/claims/_form_layout_wrapper.haml
  app/views/external_users/claims/offence_details/_fee_reform_fields.html.haml
  spec/javascripts/Modules.OffenceSearchInput_spec.js
  vendor/assets/javascripts/jquery.ba-throttle-debounce.js
  vendor/assets/javascripts/jquery.highlight-5.min.js
  vendor/assets/javascripts/jsrender.min.js
Labels: enhancement, frontend
