Repository ministryofjustice/Claim-for-Crown-Court-Defence, pull requests merged in 2018-05, with the labels that each got.

#2354 Bug fix: CSS leak
  app/assets/stylesheets/moj/_autocomplete.scss
Labels: bug, frontend, ready

#2355 Ui: Conditional CSS loading
  app/assets/stylesheets/v1/_application_prep.scss
  app/assets/stylesheets/v1/api-documentation.scss
  app/assets/stylesheets/v1/application.css.scss
  app/assets/stylesheets/v1/datatables.min.scss
  app/assets/stylesheets/v1/moj/_HOTFIX_KILLME.scss
  app/assets/stylesheets/v1/moj/_accordion.scss
  app/assets/stylesheets/v1/moj/_autocomplete.scss
  app/assets/stylesheets/v1/moj/_buttons.scss
  app/assets/stylesheets/v1/moj/_config.scss
  app/assets/stylesheets/v1/moj/_filters.scss
  app/assets/stylesheets/v1/moj/_forms.scss
  app/assets/stylesheets/v1/moj/_gds_radios.scss
  app/assets/stylesheets/v1/moj/_govuk_overrides.scss
  app/assets/stylesheets/v1/moj/_helpers.scss
  app/assets/stylesheets/v1/moj/_icons.scss
  app/assets/stylesheets/v1/moj/_layout.scss
  app/assets/stylesheets/v1/moj/_messages.scss
  app/assets/stylesheets/v1/moj/_navigation.scss
  app/assets/stylesheets/v1/moj/_print.scss
  app/assets/stylesheets/v1/moj/_related.scss
  app/assets/stylesheets/v1/moj/_shame.scss
  app/assets/stylesheets/v1/moj/_spinner.scss
  app/assets/stylesheets/v1/moj/_tables.scss
  app/assets/stylesheets/v1/moj/_typography.scss
  app/assets/stylesheets/v1/statuses.scss
  app/assets/stylesheets/v2/application.scss
  app/views/case_workers/admin/case_workers/index.html.haml
  app/views/external_users/claims/index.html.haml
  app/views/layouts/application.html.haml
Labels: enhancement, frontend, ready

#2362 Ui fixed fees redesign
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/modules/Modules.HideErrorOnChange.js
  app/assets/javascripts/modules/external_users/claims/FeeFieldsDisplay.js
  app/assets/stylesheets/v1/application.css.scss
  app/assets/stylesheets/v2/_autocomplete.scss
  app/assets/stylesheets/v2/_buttons.scss
  app/assets/stylesheets/v2/_denote.scss
  app/assets/stylesheets/v2/_forms.scss
  app/assets/stylesheets/v2/_mod-fees.scss
  app/assets/stylesheets/v2/_project-helpers.scss
  app/assets/stylesheets/v2/_sidebar.scss
  app/assets/stylesheets/v2/application.scss
  app/form_builders/adp_text_field.rb
  app/helpers/external_users/claims_helper.rb
  app/models/fee/base_fee.rb
  app/models/fee/basic_fee.rb
  app/views/external_users/advocates/claims/_fixed_fees_form_step.html.haml
  app/views/external_users/claims/_date_attended_fields.html.haml
  app/views/external_users/claims/_date_attended_fields_condensed.html.haml
  app/views/external_users/claims/basic_fees/_basic_fee_fields.html.haml
  app/views/external_users/claims/basic_fees/_fields.html.haml
  app/views/external_users/claims/fixed_fees/_fields.html.haml
  app/views/external_users/claims/fixed_fees/_fixed_fee_fields.html.haml
  app/views/external_users/claims/misc_fees/_misc_fee_fields.html.haml
  config/locales/en.yml
  features/page_objects/claim_form_page.rb
  features/page_objects/sections/expense_section.rb
  spec/form_builders/adp_text_field_spec.rb
  spec/javascripts/modules-HideErrorOnChange_spec.js
Labels: enhancement, frontend, ready

#2364 Quieten RSpec output
  app/controllers/errors_controller.rb
  app/controllers/offences_controller.rb
  app/controllers/user_message_statuses_controller.rb
  spec/api/posting_to_root_spec.rb
  spec/controllers/case_workers/admin/allocations_controller_spec.rb
  spec/controllers/case_workers/claims_controller_spec.rb
  spec/controllers/offences_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/rails_helper.rb
  spec/support/strong_paramas_helpers.rb
  spec/views/case_workers/claims/show_spec.rb
Labels: ready

#2366 AGFS: Misc fees design implementation
  app/assets/stylesheets/v2/_mod-fees.scss
  app/views/external_users/advocates/claims/_fixed_fees_form_step.html.haml
  app/views/external_users/advocates/claims/_miscellaneous_fees_form_step.html.haml
  app/views/external_users/claims/_fees_shared_header.html.haml
  app/views/external_users/claims/misc_fees/_fields.html.haml
  app/views/external_users/claims/misc_fees/_misc_fee_fields.html.haml
  config/locales/en.yml
  features/page_objects/claim_form_page.rb
  features/page_objects/sections/fee_dates_section.rb
  features/page_objects/sections/fee_dates_section_condensed.rb
  features/page_objects/sections/typed_fee_section.rb
  features/step_definitions/advocate_claim_steps.rb
Labels: enhancement, frontend

#2363 Update API template to use v1 css
  app/views/grape_swagger_rails/application/index.html.erb
Labels: enhancement, frontend, ready

#2376 general hidden classes
  app/assets/stylesheets/v2/_project-helpers.scss
Labels: enhancement, frontend, ready

#2377 Hide additional case numbers on fixed fees
  app/assets/javascripts/modules/external_users/claims/FeeFieldsDisplay.js
  features/claims/advocate/advocate_contempt_claim_edit_submit.feature
  features/page_objects/sections/typed_fee_section.rb
  features/step_definitions/advocate_claim_steps.rb
Labels: in progress

#2375 "Check your claim" page fixes
  .rubocop.yml
  app/controllers/external_users/litigators/interim_claims_controller.rb
  app/models/claim/interim_claim.rb
  app/models/claims/calculations.rb
  app/presenters/claim/interim_claim_presenter.rb
  app/views/external_users/claims/_summary_claims_content.html.haml
  app/views/external_users/claims/disbursements/_summary.html.haml
  app/views/external_users/claims/offence_details/_default_summary.html.haml
  spec/presenters/claim/interim_claim_presenter_spec.rb
Labels: ready

#2381 Patch autosave associations to support conditional validations
  app/controllers/external_users/claims_controller.rb
  app/models/claim/advocate_claim.rb
  app/models/claim/advocate_interim_claim.rb
  app/models/claim/base_claim.rb
  app/models/claim/interim_claim.rb
  app/models/claim/litigator_claim.rb
  app/models/claim/transfer_claim.rb
  app/presenters/claim/base_claim_presenter.rb
  app/validators/claim/base_claim_sub_model_validator.rb
  app/validators/claim/base_claim_validator.rb
  app/views/external_users/claims/buttons/_continue.html.haml
  config/initializers/01_autosave_association_patch.rb
  features/step_definitions/authorise_claim_steps.rb
  features/step_definitions/claim_allocation_steps.rb
  spec/api/v2/cclf_claim_spec.rb
  spec/api/v2/ccr_claim_spec.rb
  spec/controllers/external_users/advocates/claims_controller_spec.rb
  spec/controllers/external_users/advocates/interim_claims_controller_spec.rb
  spec/controllers/external_users/litigators/interim_claims_controller_spec.rb
  spec/factories/claim/litigator_claims.rb
  spec/factories/fee_types.rb
  spec/factories/fees.rb
  spec/models/claim/base_claim_spec.rb
  spec/models/claim/litigator_claim_spec.rb
  spec/models/claim_state_transition_reason_spec.rb
  spec/models/claims/state_machine_spec.rb
  spec/models/fee/base_fee_spec.rb
  spec/services/ccr/daily_attendance_adapter_spec.rb
  spec/services/claims/create_draft_spec.rb
  spec/validators/claim/interim_claim_validator_spec.rb
  spec/validators/claim/shared_examples_for_advocate_litigator.rb
  spec/validators/claim/transfer_claim_validator_spec.rb
  spec/validators/fee/base_fee_validator_spec.rb
Labels: in progress

#2374 Upgrade paper_trail gem to most recent version
  Gemfile
  Gemfile.lock
  app/controllers/external_users/claims_controller.rb
Labels: in progress

#2386 HOTFIX: Already submitted claim check should be done on the claim itself
  app/services/claims/claim_actions_service.rb
Labels: in progress

#2385 Quantity for a fee needs to be greater or equal than 1
  app/validators/fee/base_fee_validator.rb
  app/validators/fee/basic_fee_validator.rb
  spec/support/shared_examples_for_fee_validators.rb
  spec/validators/fee/base_fee_validator_spec.rb
  spec/validators/fee/fixed_fee_validator_spec.rb
Labels: ready

#2373 CBO-105 LGFS Misc Fees design
  app/assets/stylesheets/v2/_mod-fees.scss
  app/models/fee/base_fee.rb
  app/views/external_users/claims/_summary_fee.html.haml
  app/views/external_users/claims/misc_fees/litigators/_fields.html.haml
  app/views/external_users/claims/misc_fees/litigators/_misc_fee_fields.html.haml
  app/views/external_users/litigators/claims/_miscellaneous_fees_form_step.html.haml
  app/views/external_users/litigators/transfer_claims/_miscellaneous_fees_form_step.html.haml
  config/locales/en.yml
  features/page_objects/litigator_claim_form_page.rb
  features/step_definitions/litigator_claim_steps.rb
Labels: enhancement, frontend, ready

#2387 Disable NewRelic monitor for non-prod environments
  config/newrelic.yml
Labels: in progress

#2378 CBO-28 Mute "attach indictment" pop up for fixed fees
  app/views/external_users/claims/basic_fees/_fields.html.haml
  app/views/external_users/claims/fixed_fees/_fields.html.haml
  app/views/external_users/claims/fixed_fees/litigators/_fields.html.haml
  app/views/external_users/claims/graduated_fees/_fields.html.haml
  app/views/external_users/claims/supporting_evidence_checklist/_fields.html.haml
Labels: enhancement, frontend, ready
