Repository ministryofjustice/Claim-for-Crown-Court-Defence, pull requests merged in 2018-02, with the labels that each got.

#2240 Core govuk dependencies update
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/stylesheets/_application_prep.scss
  app/assets/stylesheets/moj/_autocomplete.scss
  app/assets/stylesheets/moj/_forms.scss
  app/assets/stylesheets/moj/_shame.scss
  app/assets/stylesheets/moj/_tables.scss
  app/views/case_workers/admin/case_workers/_form.html.haml
  app/views/external_users/admin/external_users/_form.html.haml
  app/views/external_users/certifications/new.html.haml
  app/views/external_users/claim_types/selection.html.haml
  app/views/external_users/claims/case_details/_cracked_trial_fields.html.haml
  app/views/external_users/claims/case_details/_fields.html.haml
  app/views/external_users/claims/case_details/_retrial_detail_fields.html.haml
  app/views/external_users/claims/defendants/_defendant_fields.html.haml
  app/views/external_users/claims/expenses/_expense_fields.html.haml
  app/views/external_users/claims/supplier_number/_fields.html.haml
  app/views/external_users/claims/supporting_documents/_disk_evidence.html.haml
  app/views/external_users/claims/supporting_evidence_checklist/_evidence_checklist.html.haml
  app/views/external_users/claims/supporting_evidence_checklist/_fields.html.haml
  app/views/external_users/claims/transfer_fee/_detail_fields.html.haml
  app/views/feedback/feedback.html.haml
  app/views/shared/_determinations_form.html.haml
  app/views/shared/_message_controls.html.haml
  app/views/super_admins/external_users/_form.html.haml
  app/views/super_admins/providers/_form.html.haml
  config/initializers/assets.rb
  features/page_objects/certification_page.rb
  features/page_objects/claim_show_page.rb
  features/page_objects/fee_scheme_selector_page.rb
  features/page_objects/sections/retrial_section.rb
  features/page_objects/sections/supplier_numbers_section.rb
  features/page_objects/sections/transfer_fee_section.rb
  features/step_definitions/advocate_claim_steps.rb
  features/step_definitions/common_steps.rb
Labels: enhancement, frontend, ready

#2242 MI fix
  app/presenters/claim_csv_presenter.rb
Labels: donotmerge

#2244 Re-Allocation page bugs
  app/assets/javascripts/modules/Modules.SelectAll.js
  app/views/case_workers/admin/allocations/_orig_scheme_filters.html.haml
  app/views/case_workers/admin/allocations/_re_allocation.html.haml
Labels: bug, frontend, ready

#2250 Error messages: new style radios
  app/assets/stylesheets/moj/_forms.scss
  config/initializers/config.rb
Labels: bug, frontend, ready

#2254 Conditionally expose warrant attributes for interim fees
  app/interfaces/api/entities/cclf/adapted_interim_fee.rb
  spec/api/entities/cclf/adapted_disbursement_spec.rb
  spec/api/entities/cclf/adapted_expense_spec.rb
  spec/api/entities/cclf/adapted_fixed_fee_spec.rb
  spec/api/entities/cclf/adapted_graduated_fee_spec.rb
  spec/api/entities/cclf/adapted_interim_fee_spec.rb
  spec/api/entities/cclf/adapted_misc_fee_spec.rb
  spec/api/entities/cclf/adapted_warrant_fee_spec.rb
  spec/services/cclf/disbursement_adapter_spec.rb
  spec/services/cclf/fee/shared_examples_for_cclf_fee_adapters.rb
  spec/support/shared_examples_for_fee_adapters.rb
Labels: ready

#2257 New style radio button fixes
  app/views/shared/_scheme_filters.html.haml
Labels: bug, frontend, ready
