Repository ministryofjustice/Claim-for-Crown-Court-Defence, pull requests merged in 2019-03, with the labels that each got.

#2677 Amend release notes to correct path to new claims endpoints
  app/views/pages/api_release_notes.html.haml
Labels: ready

#2682 Bug fix: management information link
  config/locales/en.yml
Labels: bug

#2687 CBO-639: Numbering for multi item lists
  app/assets/javascripts/plugins/jquery.numbered.elements.js
  features/claims/advocate/scheme_nine/advocate_admin_trial_claim_edit_submit.feature
  features/claims/advocate/scheme_ten/advocate_expense_page.feature
  features/claims/advocate/scheme_ten/advocate_trial_claim_edit_submit.feature
  features/claims/litigator/litigator_expense_page.feature
Labels: enhancement, frontend, ready

#2686 CBO-642: Re/Allocation page review
  app/assets/javascripts/modules/Modules.AllocationDataTable.js
  app/assets/javascripts/modules/case_worker/Allocation.js
  app/assets/javascripts/modules/case_worker/ReAllocation.js
  app/assets/stylesheets/v2/_autocomplete.scss
  app/assets/stylesheets/v2/_datatables.scss
  app/assets/stylesheets/v2/_tables.scss
  app/assets/stylesheets/v2/application.scss
  app/views/case_workers/admin/allocations/_allocation.html.haml
  app/views/case_workers/admin/allocations/_filter_tasks.html.haml
  app/views/case_workers/admin/allocations/_filter_value_bands.html.haml
  app/views/case_workers/admin/allocations/_re_allocation.html.haml
  app/views/shared/_search_form.html.haml
  features/page_objects/allocation_page.rb
  features/step_definitions/caseworker_claim_allocation_steps.rb
  spec/javascripts/Modules.AllocationDataTable_spec.js
  spec/javascripts/Modules.Allocation_spec.js
Labels: enhancement, frontend, ready

#2688 CBO-640: Case details page review
  app/views/external_users/advocates/claims/_case_details_form_step.html.haml
  app/views/external_users/advocates/interim_claims/_case_details_form_step.html.haml
  app/views/external_users/advocates/supplementary_claims/_case_details_form_step.html.haml
  app/views/external_users/claims/case_details/_fields.html.haml
  app/views/external_users/claims/supplier_number/_fields.html.haml
  app/views/external_users/litigators/claims/_case_details_form_step.html.haml
  app/views/external_users/litigators/interim_claims/_case_details_form_step.html.haml
  app/views/external_users/litigators/transfer_claims/_case_details_form_step.html.haml
  config/locales/en.yml
Labels: enhancement, frontend, in progress
