Repository ministryofjustice/Claim-for-Crown-Court-Defence, pull requests merged in 2019-02, with the labels that each got.

#2643 CBO-570 Accessibility: Offence details page review
  app/assets/javascripts/modules/external_users/claims/NewClaim.js
  app/assets/javascripts/modules/external_users/claims/OffenceCtrl.js
  app/views/external_users/claims/offence_details/_default_fields.html.haml
  app/views/offences/index.js.erb
  features/page_objects/claim_form_page.rb
  features/step_definitions/common_steps.rb
  spec/javascripts/Modules.OffenceCtrl_spec.js
Labels: enhancement, frontend

#2640 Cbo 560 redetermination last caseworker
  README.md
  app/presenters/claim_csv_presenter.rb
  config/initializers/inflections.rb
  config/settings.yml
  spec/presenters/claim_csv_presenter_spec.rb
  spec/services/stats/management_information_generator_spec.rb
Labels: in progress

#2645 CBO-574: Disbursement page review
  app/assets/javascripts/application.js
  app/assets/javascripts/modules/external_users/claims/DisbursementsCtrl.js
  app/assets/javascripts/modules/external_users/claims/InterimFeeFieldsDisplay.js
  app/assets/stylesheets/v1/application.css.scss
  app/assets/stylesheets/v1/moj/_autocomplete.scss
  app/assets/stylesheets/v2/_autocomplete.scss
  app/views/external_users/claims/case_details/_fields.html.haml
  app/views/external_users/claims/disbursements/_disbursement_fields.html.haml
  app/views/external_users/claims/disbursements/_fields.html.haml
  app/views/external_users/claims/interim_fee/_fields.html.haml
  app/views/external_users/litigators/claims/_disbursements_form_step.html.haml
  features/claims/litigator/interim_trial_claim_draft_submit.feature
  features/claims/litigator/litigator_contempt_claim_draft_submit.feature
  features/claims/litigator/litigator_trial_claim_draft_submit.feature
  features/claims/litigator/transfer_claim_draft_submit.feature
  features/page_objects/litigator_claim_form_page.rb
  features/page_objects/sections/disbursement_section.rb
  features/step_definitions/litigator_claim_steps.rb
  spec/javascripts/Modules.DisbursementCtrl_spec.js
  vendor/assets/stylesheets/accessible-autocomplete.scss
Labels: enhancement, frontend, ready

#2652 CBO-587: Transfer fees
  app/assets/javascripts/modules/external_users/claims/TransferDetailFieldsDisplay.js
  app/assets/javascripts/modules/external_users/claims/TransferDetailsCtrl.js
  app/assets/stylesheets/v2/_autocomplete.scss
  app/presenters/claim/transfer_claim_presenter.rb
  app/views/external_users/claims/transfer_fee/_detail_fields.html.haml
  app/views/external_users/litigators/transfer_claims/_transfer_fee_details_form_step.html.haml
  config/locales/en.yml
  features/fee_calculator/litigator/transfer_fee_calculator.feature
  features/page_objects/litigator_transfer_claim_form_page.rb
  features/page_objects/sections/lgfs_transfer_detail_section.rb
  features/step_definitions/litigator_transfer_claim_steps.rb
  spec/presenters/claim/transfer_claim_presenter_spec.rb
Labels: enhancement, frontend, ready
