Repository ministryofjustice/Claim-for-Crown-Court-Defence, pull requests merged in 2019-11, with the labels that each got.

#3050 CBO-777: Basic accessibility checks
  app/assets/stylesheets/_buttons.scss
  app/assets/stylesheets/_cccd-typography.scss
  app/assets/stylesheets/_layout.scss
  app/assets/stylesheets/_mod-fees.scss
  app/assets/stylesheets/_navigation.scss
  app/assets/stylesheets/_project-helpers.scss
  app/assets/stylesheets/_shame.scss
  app/form_builders/adp_text_field.rb
  app/views/case_workers/admin/allocations/_re_allocation.html.haml
  app/views/errors/_error_summary.html.haml
  app/views/errors/_injection_error_summary.html.haml
  app/views/external_users/advocates/_advocate_category.html.haml
  app/views/external_users/claim_types/selection.html.haml
  app/views/external_users/claims/_agfs_final_claim_sidebar.html.haml
  app/views/external_users/claims/_agfs_interim_claim_sidebar.html.haml
  app/views/external_users/claims/_agfs_supplementary_claim_sidebar.html.haml
  app/views/external_users/claims/_financial_summary.html.haml
  app/views/external_users/claims/_lgfs_final_claim_sidebar.html.haml
  app/views/external_users/claims/_lgfs_interim_claim_sidebar.html.haml
  app/views/external_users/claims/_lgfs_transfer_claim_sidebar.html.haml
  app/views/external_users/claims/case_details/_fields.html.haml
  app/views/external_users/claims/defendants/_defendant_fields.html.haml
  app/views/external_users/claims/expenses/_expense_fields.html.haml
  app/views/external_users/claims/expenses/_fields.html.haml
  app/views/external_users/claims/index.html.haml
  app/views/external_users/claims/interim_fee/_fields.html.haml
  app/views/external_users/claims/misc_fees/advocates/_misc_fee_fields.html.haml
  app/views/external_users/claims/offence_details/_default_fields.html.haml
  app/views/external_users/claims/supplier_number/_fields.html.haml
  app/views/external_users/claims/supporting_documents/_disk_evidence.html.haml
  app/views/kaminari/_first_page.html.haml
  app/views/kaminari/_gap.html.haml
  app/views/kaminari/_last_page.html.haml
  app/views/kaminari/_next_page.html.haml
  app/views/kaminari/_page.html.haml
  app/views/kaminari/_paginator.html.haml
  app/views/kaminari/_prev_page.html.haml
  app/views/layouts/_contact_us_link.html.haml
  app/views/layouts/_primary_navigation.html.haml
  app/views/layouts/application.html.haml
  app/views/layouts/claim_forms.html.haml
  app/views/layouts/statistics.html.haml
  app/views/shared/_claim_accordion.html.haml
  app/views/shared/_determinations_table.html.haml
  app/views/shared/_summary_agfs.html.haml
  app/views/shared/_summary_totals.html.haml
  app/views/warnings/_conference_and_views_summary.html.haml
  config/locales/en.yml
  features/page_objects/claim_form_page.rb
  features/step_definitions/common_steps.rb
  spec/form_builders/adp_text_field_spec.rb
Labels: frontend

#3061 Correct docker tag naming
  .circleci/config.yml
Labels: hotfix

#3047 Downtime warning banner
  app/assets/stylesheets/_cccd-typography.scss
  app/assets/stylesheets/_shame.scss
  app/helpers/claims_helper.rb
  app/views/external_users/shared/_timed_retention_banner.html.haml
  app/views/shared/_downtime_warning.html.haml
  app/views/shared/_phase_banner.haml
  config/locales/en.yml
  config/settings.yml
  features/claims/downtime_banner.feature
  features/step_definitions/common_claim_steps.rb
  features/step_definitions/common_steps.rb
  features/step_definitions/downtime_banner_steps.rb
  features/support/hooks.rb
  spec/helpers/claims_helper_spec.rb
Labels: donotmerge

#3075 CBO-994: Stylesheet refactoring, remove magic values
  app/assets/stylesheets/_accordion.scss
  app/assets/stylesheets/_autocomplete.scss
  app/assets/stylesheets/_breadcrumbs.scss
  app/assets/stylesheets/_buttons.scss
  app/assets/stylesheets/_callout.scss
  app/assets/stylesheets/_cccd-typography.scss
  app/assets/stylesheets/_claims_importer.scss
  app/assets/stylesheets/_denote.scss
  app/assets/stylesheets/_forms.scss
  app/assets/stylesheets/_layout.scss
  app/assets/stylesheets/_links.scss
  app/assets/stylesheets/_lists.scss
  app/assets/stylesheets/_messages.scss
  app/assets/stylesheets/_mod-fees.scss
  app/assets/stylesheets/_mod-provider-details.scss
  app/assets/stylesheets/_navigation.scss
  app/assets/stylesheets/_panels.scss
  app/assets/stylesheets/_print.scss
  app/assets/stylesheets/_related.scss
  app/assets/stylesheets/_shame.scss
  app/assets/stylesheets/_tables.scss
  app/assets/stylesheets/_warnings.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/cccd-measurements.scss
  app/assets/stylesheets/statuses.scss
  app/views/external_users/claims/confirmation.html.haml
  app/views/external_users/claims/offence_details/_fee_reform_fields.html.haml
  app/views/external_users/claims/warrant_fee/_fields.html.haml
Labels: frontend

#3081 MIGRATION DAY: Turn of maintenance mode on live-1 production permanently
  kubernetes_deploy/production/deployment.yaml
Labels: donotmerge, kubernetes migration

#3072 MIGRATION DAY: live-1 production ingress DONOTMERGE til cutover day.
  kubernetes_deploy/production/ingress.yaml
Labels: donotmerge, kubernetes migration

#3048 MIGRATION DAY: Amend env var inline with eventual live-1 domain name
  kubernetes_deploy/production/deployment.yaml
Labels: donotmerge, kubernetes migration

#3083 MIGRATION DAY: Switch off downtime warning banner
  config/settings.yml
Labels: donotmerge, kubernetes migration

#3078 CBO-992: Stylesheet refactoring, remove inline styles
  app/assets/javascripts/modules/Modules.AllocationDataTable.js
  app/assets/javascripts/modules/Modules.AmountAssessed.js
  app/assets/javascripts/modules/Modules.OffenceSearchInput.js
  app/assets/javascripts/modules/Modules.OffenceSearchView.js
  app/assets/javascripts/modules/Plugin.jqDataTable.filter.js
  app/assets/javascripts/modules/external_users/claims/BlockHelpers.js
  app/assets/javascripts/modules/external_users/claims/CaseTypeCtrl.js
  app/assets/javascripts/modules/external_users/claims/TransferDetailFieldsDisplay.js
  app/assets/javascripts/modules/external_users/claims/fee_calculator/FeeCalculator.GraduatedPrice.js
  app/assets/javascripts/modules/external_users/claims/fee_calculator/FeeCalculator.UnitPrice.js
  app/assets/javascripts/plugins/jquery.numbered.elements.js
  app/assets/stylesheets/_forms.scss
  app/assets/stylesheets/_links.scss
  app/assets/stylesheets/_shame.scss
  app/views/case_workers/admin/allocations/_allocation.html.haml
  app/views/case_workers/admin/allocations/_filter_tasks.html.haml
  app/views/case_workers/admin/allocations/_filter_value_bands.html.haml
  app/views/case_workers/admin/allocations/_re_allocation.html.haml
  app/views/devise/registrations/new.html.haml
  app/views/external_users/claims/basic_fees/_additional_fee_fields.html.haml
  app/views/external_users/claims/basic_fees/_basic_fee_fields_primary.html.haml
  app/views/external_users/claims/basic_fees/_extra_fee_fields.html.haml
  app/views/external_users/claims/case_details/_cracked_trial_fields.html.haml
  app/views/external_users/claims/case_details/_retrial_detail_fields.html.haml
  app/views/external_users/claims/case_details/_trial_detail_fields.html.haml
  app/views/external_users/claims/defendants/_defendant_fields.html.haml
  app/views/external_users/claims/defendants/_representation_order_fields.html.haml
  app/views/external_users/claims/disbursements/_disbursement_fields.html.haml
  app/views/external_users/claims/expenses/_expense_fields.html.haml
  app/views/external_users/claims/fixed_fees/advocates/_fixed_fee_fields.html.haml
  app/views/external_users/claims/fixed_fees/litigators/_fields.html.haml
  app/views/external_users/claims/graduated_fees/_fields.html.haml
  app/views/external_users/claims/misc_fees/advocates/_misc_fee_fields.html.haml
  app/views/external_users/claims/misc_fees/advocates/supplementary/_misc_fee_fields.html.haml
  app/views/external_users/claims/misc_fees/litigators/_misc_fee_fields.html.haml
  app/views/external_users/claims/offence_details/_fee_reform_fields.html.haml
  app/views/external_users/claims/transfer_fee/_detail_fields.html.haml
  app/views/external_users/claims/transfer_fee/_fields.html.haml
  app/views/shared/_claim_header.html.haml
  app/views/shared/_determinations_form.html.haml
  app/views/shared/_evidence_list.html.haml
  app/views/shared/_supplier_number_fields.html.haml
  spec/javascripts/Modules.OffenceSearchInput_spec.js
  spec/javascripts/helpers-sidebar_spec.js
  spec/javascripts/modules-amountAssessed_spec.js
Labels: frontend

#3069 CBO-993: Stylesheet refactoring, remove duplicate rules
  app/assets/stylesheets/_cccd-typography.scss
  app/assets/stylesheets/_denote.scss
  app/assets/stylesheets/_forms.scss
  app/assets/stylesheets/_mod-fees.scss
  app/assets/stylesheets/_navigation.scss
  app/assets/stylesheets/_panels.scss
  app/assets/stylesheets/_print.scss
  app/assets/stylesheets/_related.scss
  app/assets/stylesheets/_shame.scss
  app/assets/stylesheets/_tables.scss
  app/assets/stylesheets/_warnings.scss
Labels: frontend
