Repository ministryofjustice/Claim-for-Crown-Court-Defence, pull requests merged in 2022-06, with the labels that each got.

#4730 [SPIKE] [CFP-403] FormBuilder migration- Fixed fees
  app/controllers/external_users/application_controller.rb
  app/controllers/external_users/claims_controller.rb
  app/form_builders/adp_text_field.rb
  app/models/date_attended.rb
  app/models/fee/fixed_fee.rb
  app/presenters/error_message/presenter.rb
  app/presenters/fee/base_fee_presenter.rb
  app/validators/base_sub_model_validator.rb
  app/validators/concerns/claim/advocate_claim_common_validations.rb
  app/validators/date_attended_validator.rb
  app/validators/fee/base_fee_validator.rb
  app/validators/fee/concerns/case_numbers_validator.rb
  app/views/external_users/advocates/_advocate_category.html.haml
  app/views/external_users/claims/_date_attended_fields.html.haml
  app/views/external_users/claims/_error_summary.html.haml
  app/views/external_users/claims/fixed_fees/advocates/_fields.html.haml
  app/views/external_users/claims/fixed_fees/advocates/_fixed_fee_fields.html.haml
  app/views/external_users/claims/fixed_fees/litigators/_fields.html.haml
  app/webpack/javascripts/modules/external_users/claims/fee_calculator/FeeCalculator.UnitPrice.js
  app/webpack/stylesheets/_shame.scss
  config/locales/en.yml
  config/locales/en/error_messages/claim.yml
  config/locales/en/models/claim.yml
  features/claims/advocate/scheme_eleven/advocate_fixed_fee_claim_submit.feature
  features/page_objects/claim_form_page.rb
  features/page_objects/sections/advocate_category_section.rb
  features/page_objects/sections/checklist_section.rb
  features/page_objects/sections/fee_dates_section.rb
  features/page_objects/sections/fee_dates_section_condensed.rb
  features/page_objects/sections/fee_section.rb
  features/page_objects/sections/fixed_fee_case_numbers_section.rb
  features/page_objects/sections/fixed_fee_section.rb
  features/page_objects/sections/lgfs_fixed_fee_section.rb
  features/page_objects/sections/typed_fee_section.rb
  features/step_definitions/advocate_claim_steps.rb
  features/step_definitions/govuk_component_steps.rb
  spec/controllers/external_users/litigators/claims_controller_spec.rb
  spec/form_builders/adp_text_field_spec.rb
  spec/support/shared_examples/validators/shared_examples_for_advocate_claim_validators.rb
  spec/support/shared_examples_for_fee_validators.rb
  spec/support/validation_helpers.rb
  spec/validators/claim/advocate_interim_claim_web_validations_spec.rb
  spec/validators/date_attended_validator_spec.rb
  spec/validators/fee/base_fee_validator_spec.rb
  spec/validators/fee/fixed_fee_validator_spec.rb
  spec/validators/fee/graduated_fee_validator_spec.rb
  spec/validators/fee/misc_fee_validator_spec.rb
Labels: ready for review, Form Builder

#4874 [SPIKE] [CFP-410] FormBuilder migration - Travel expenses
  app/controllers/external_users/claims_controller.rb
  app/models/expense.rb
  app/validators/base_sub_model_validator.rb
  app/validators/base_validator.rb
  app/validators/expense_validator.rb
  app/views/external_users/claims/_error_summary.html.haml
  app/views/external_users/claims/expenses/_expense_fields.html.haml
  app/views/external_users/claims/expenses/_fields.html.haml
  app/views/external_users/claims/expenses/_textarea_additional_info.html.haml
  config/locales/en.yml
  config/locales/en/error_messages/claim.yml
  config/locales/en/models/claim.yml
  features/claims/litigator/litigator_contempt_claim_with_errors_submit.feature
  features/page_objects/sections/expense_section.rb
  spec/api/v1/external_users/expense_spec.rb
  spec/models/claim/advocate_claim_spec.rb
  spec/validators/claim/advocate_interim_claim_web_validations_spec.rb
  spec/validators/expense_validator_spec.rb
Labels: ready for review, Form Builder

#4942 Validate case type for interim claims
  .rubocop_todo.yml
  app/validators/claim/interim_claim_validator.rb
  spec/controllers/external_users/litigators/interim_claims_controller_spec.rb
  spec/factories/claim/interim_claims.rb
  spec/models/claim/interim_claim_spec.rb
  spec/validators/claim/interim_claim_validator_spec.rb
Labels: approved

#4848 [CFP-77] FormBuilder migration - Graduated fees
  app/controllers/external_users/claims_controller.rb
  app/models/fee/graduated_fee.rb
  app/presenters/error_message/presenter.rb
  app/validators/base_sub_model_validator.rb
  app/validators/claim/base_claim_validator.rb
  app/validators/fee/graduated_fee_validator.rb
  app/views/external_users/claims/_error_summary.html.haml
  app/views/external_users/claims/graduated_fees/_fields.html.haml
  config/locales/en.yml
  config/locales/en/error_messages/claim.yml
  config/locales/en/models/claim.yml
  features/page_objects/litigator_claim_form_page.rb
  spec/controllers/external_users/litigators/claims_controller_spec.rb
  spec/presenters/error_message/presenter_spec.rb
  spec/support/shared_examples_for_fee_validators.rb
  spec/support/validation_helpers.rb
  spec/validators/claim/base_claim_validator_spec.rb
  spec/validators/fee/base_fee_validator_spec.rb
  spec/validators/fee/graduated_fee_validator_spec.rb
Labels: Form Builder, approved

#4960 [CFP-352] FormBuilder migration - Hardship fees
  app/validators/base_sub_model_validator.rb
  app/validators/fee/hardship_fee_validator.rb
  app/views/external_users/claims/_error_summary.html.haml
  app/views/external_users/claims/hardship_fee/_fields.html.haml
  config/locales/en/error_messages/claim.yml
  config/locales/en/models/claim.yml
  spec/support/shared_examples_for_fee_validators.rb
  spec/validators/fee/hardship_fee_validator_spec.rb
Labels: ready for review, Form Builder, approved

#4980 Sonarcloud code analysis
  app/webpack/javascripts/modules/Modules.AllocationDataTable.js
  app/webpack/javascripts/modules/external_users/claims/FeeTypeCtrl.js
  app/webpack/javascripts/modules/show-hide-content.js
  spec/javascripts/Modules.AllocationDataTable_spec.js
  spec/javascripts/Modules.Autocomplete_spec.js
  spec/javascripts/Modules.OffenceSearchInput_spec.js
  spec/javascripts/helpers-sidebar_spec.js
  spec/javascripts/helpers/jasmine-jquery.js
  spec/javascripts/modules-amountAssessed_spec.js
  spec/javascripts/modules-sidebar_spec.js
  spec/javascripts/supporting-evidence_spec.js
Labels: approved
