Repository ministryofjustice/Claim-for-Crown-Court-Defence, pull requests merged in 2022-04, with the labels that each got.

#4799 [CFP-541] Improve feedback tasks mechanism
  app/views/feedback/feedback.html.haml
  config/locales/en/views/feedback.yml
Labels: approved

#4785 [CFP-502] Enable ModSecurity WAF on dev
  .k8s/live/dev/ingress.yaml
Labels: approved

#4786 [CFP-502] Enable ModSecurity WAF on dev-lgfs
  .k8s/live/dev-lgfs/ingress.yaml
Labels: approved

#4788 [CFP-502] Enable ModSecurity WAF on staging
  .k8s/live/dev-lgfs/ingress.yaml
  .k8s/live/dev/ingress.yaml
  .k8s/live/staging/ingress.yaml
Labels: approved

#4800 CFP-502 Enable ModSecurity WAF on api-sandbox
  .k8s/live/api-sandbox/ingress.yaml
Labels: approved

#4787 [CFP-502] Enable ModSecurity WAF on production
  .k8s/live/production/ingress.yaml
Labels: approved

#4821 [Security] Selectively add package: Async
  package.json
  yarn.lock
Labels: approved

#4831 Update deprecated Sidekiq.default_worker_options call
  config/initializers/sidekiq.rb
Labels: ready for review

#4822 CFP-485 Add rake task to identify and disable inactive users
  lib/tasks/inactive_users.rake
  lib/tasks/rake_helpers/user_management.rb
Labels: ready for review

#4835 Refactor rspec shared examples
  spec/api/v1/external_users/date_attended_spec.rb
  spec/api/v1/external_users/defendant_spec.rb
  spec/api/v1/external_users/disbursement_spec.rb
  spec/api/v1/external_users/expense_spec.rb
  spec/api/v1/external_users/fee_spec.rb
  spec/api/v1/external_users/representation_order_spec.rb
  spec/support/shared_examples_for_api.rb
Labels: ready for review

#4823 [CFP-370] FormBuilder migration - Defendants details
  .rubocop_todo.yml
  app/controllers/external_users/claims_controller.rb
  app/models/defendant.rb
  app/models/representation_order.rb
  app/validators/base_sub_model_validator.rb
  app/validators/defendant_validator.rb
  app/validators/representation_order_validator.rb
  app/views/external_users/claims/_error_summary.html.haml
  app/views/external_users/claims/defendants/_defendant_fields.html.haml
  app/views/external_users/claims/defendants/_fields.html.haml
  app/views/external_users/claims/defendants/_representation_order_fields.html.haml
  app/webpack/javascripts/modules/external_users/claims/DefendantsCtrl.js
  app/webpack/stylesheets/_cocoon.scss
  app/webpack/stylesheets/_forms.scss
  config/locales/en.yml
  config/locales/en/error_messages/claim.yml
  config/locales/en/models/claim/defendants.yml
  features/page_objects/claim_form_page.rb
  spec/api/v1/external_users/representation_order_spec.rb
  spec/controllers/external_users/litigators/claims_controller_spec.rb
  spec/controllers/external_users/litigators/interim_claims_controller_spec.rb
  spec/models/claim/advocate_claim_spec.rb
  spec/models/defendant_spec.rb
  spec/models/representation_order_spec.rb
  spec/models/timed_transitions/transitioner_spec.rb
  spec/validators/claim/advocate_interim_claim_web_validations_spec.rb
  spec/validators/claim/base_claim_sub_model_validator_spec.rb
  spec/validators/defendant_validator_spec.rb
  spec/validators/representation_order_validator_spec.rb
Labels: Form Builder, approved
